# Generated by Django 4.1.7 on 2023-02-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'director'), (2, 'manager'), (3, 'teachers'), (4, 'call center'), (5, 'students')], default=1),
        ),
    ]
